# ------------------------
# Adopta Agency Blueprint
# This is meant to be a blueprint for opening up data.
# You control everything about this site, here in the _config.yml
# All data is stored under /data
# All API definitions are stored under /api
# Tell your story via the /blog
# Manage all conversations through this project's Github issues
# ------------------------

# Give your peject a title, description, some tags, and URL to Github home page
project_title: Clinical Trials
project_description: This is an open data project to the Clinical Trials and Transformation Iniative (CTTI) Aggregate Analysis of ClincalTrials.gov (AACT) Database, and deliver a simple web API, making the information more acessible, and usable in a variety of platforms and implementations.
project_url: http://adopta-agency.github.io/clinical-trials/
project_tags:
  - tag: healthcare
  - tag: clinical trials

github_user: adopta-agency
github_repo: clinical-trials

# ---------
# This is the section where you describe the data involved in your project.
# ---------
data_show: yes
data_nav: yes
data_title: Data Files
data_description: This is just a sample set of dataset to show what is possible. Your mission, if you choose to accept, is to find a dataset at data.gov, or amongst the inventory of each federal agencies data.json files. Once you have found your datasatets, you can clean up, publish, and share here.
data_footer: The goal of publishing these CSV and JSON alternatives is to make this data easier to consumer, and integrate into websites, applications, visualizations, and other integrations.

# You can add one or many data sets here, with a title, and link to CSV and JSON file
data:
  - title: "ARM Groups"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/arm_groups.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/arm_groups.json"
  - title: "Authorities"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/authorities.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/authorities.json"
  - title: "Central Contacts"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/central_contacts.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/central_contacts.json"
  - title: "Clinical Study (noclob)"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/clinical_study_noclob.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/clinical_study_noclob.json"
  - title: "Clinical Study"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/clinical_study.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/clinical_study.json"
  - title: "Condition Browse"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/condition_browse.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/condition_browse.json"
  - title: "Conditions"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/conditions.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/conditions.json"
  - title: "Delayed Results"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/delayed_results.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/delayed_results.json"
  - title: "Designs"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/designs.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/designs.json"
  - title: "Facilities"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/facilities.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/facilities.json"
  - title: "Facility Contacts"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/facility_contacts.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/facility_contacts.json"
  - title: "Intervention ARM Groups"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/intervention_arm_groups.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/intervention_arm_groups.json"
  - title: "Intervention Browse"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/intervention_browse.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/intervention_browse.json"
  - title: "Intervention Other Names"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/intervention_other_names.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/intervention_other_names.json"
  - title: "Intervention"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/interventions.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/interventions.json"
  - title: "Keywords"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/keywords.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/keywords.json"
  - title: "Location Countries"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/location_countries.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/location_countries.json"
  - title: "Mesh Thesaurus"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/mesh_thesaurus.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/mesh_thesaurus.json"
  - title: "NCT Aliases"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/nct_aliases.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/nct_aliases.json"
  - title: "Overall Officials"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/overall_officials.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/overall_officials.json"
  - title: "References"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/references.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/references.json"
  - title: "Removed Countries"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/removed_countries.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/removed_countries.json"
  - title: "Reported Event Category Groups"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/reported_event_ctgy_grp.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/reported_event_ctgy_grp.json"
  - title: "Responsible Parties"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/responsible_parties.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/responsible_parties.json"
  - title: "Results Baseline Measure Categories"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_baseline_measure_catgy.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_baseline_measure_catgy.json"
  - title: "Results Baseline Measure"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_baseline_measure.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_baseline_measure.json"
  - title: "Results Baseline"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_baseline.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_baseline.json"
  - title: "Results Outcome Analysis Groups"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_outcome_analysis_grp.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_outcome_analysis_grp.json"
  - title: "Results Outcome Analysis"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_outcome_analysis.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_outcome_analysis.json"
  - title: "Results Outcome Measure Categories"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_outcome_measure_ctgy.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_outcome_measure_ctgy.json"
  - title: "Results Outcome Measure"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_outcome_measure.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_outcome_measure.json"
  - title: "Results Outcomes"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_outcomes.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_outcomes.json"
  - title: "Results Partflow MLSTN Group"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_partflow_mlstn_grp.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_partflow_mlstn_grp.json"
  - title: "Results Partflow MLSTN"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_partflow_mlstn.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_partflow_mlstn.json"
  - title: "Results Partflows"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_partic_flows.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_partic_flows.json"
  - title: "Results Point of Contact"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_point_of_contact.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_point_of_contact.json"
  - title: "Results Restriction Agreement"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_restriction_agreement.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/results_restriction_agreement.json"
  - title: "Secondary IDs"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/secondary_ids.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/secondary_ids.json"
  - title: "Sponsors"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/sponsors.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/sponsors.json"
  - title: "Study Outcome"
    source_url: https://clinicaltrials.gov/ct2/resources/download
    csv_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/study_outcome.csv"
    json_url: "https://s3.amazonaws.com/kinlane-productions/adopta-agency/data/clinical-trials/study_outcome.json"

# ---------
# APIs
# ---------

api_show: yes
api_nav: yes
api_title: APIs
api_description: This is a sample API generated from the dataset above. It is described using OpenAPI Spec which allows the generation of interactive documentation, while also describing the meta data and surface area of an API.
api_footer: The goal of launching these APIs is to make this data easier to consumer, and integrate into websites, applications, visualizations, and other integrations.

api:
  - title: Clinical Trials
    swagger_url: adopta-agency.github.io/clinical-trials/openapi-spec/complete.json

# ---------
# Showcase
# ---------

showcase_show: no
showcase_nav: no
showcase_title: Showcase
showcase_description: This is a showcase of what is being build on top of this open data and APIs. Right now it is just sample data, but when you launch for your project, you can showcase everything that is being developed.
showcase_footer: This project is designed to be used, and extended, please share what you have built so it can be included here on the showcase, for others to find.

showcase:
  - title: Showcase Item One
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com

# ---------
# FAQ
# ---------

faq_show: yes
faq_nav: no
faq_title: FAQ
faq_description: These are some of the common questions that need answering, or get asked as part of the work around this project.
faq_footer: Questions that get submitted via the projects Github issue managment are sometimes added here.

faq:
  - question: Why are you doing this?
    answer: Someone from the University of Miami contacted me after doing an Adopta Agency presentation, asking for help to adopt.
  - question: Where did this data come from?
    answer: It could come from ClinicalTrials.gov, and specifically from their download page located at: https://clinicaltrials.gov/ct2/resources/download.
  - question: What are you planning on doing with this data?
    answer: Get it up as a set of JSON, and CSV files, as well as an API, then decide what downloads and endpoints would make consumption easier.
  - question: How do I talk to someone behind this project?
    answer: This site runs on Github Pages, and relies on Github issue management for support. <a href="https://github.com/adopta-agency/clinical-trials/issues">Go ahead and submit an issue</a> via the project repository.

# ---------
# Team
# ---------

team_show: yes
team_nav: no
team_title: Team
team_description: This is a solo project conducted by Kin Lane as part of this Adopta.Agency project.
team_footer: If you would like to get involved with this work, please submit an issue via the Github repo.

team:
  - name: Kin Lane
    description: The API Evangelist, working to make data, content, and other digital resources more accessible.
    url: http://kinlane.com

# ---------
# Tools
# ---------

tools_show: yes
tools_nav: no
tools_title: Tools
tools_description: This is a list of tools that are used as part of this project.
tools_footer: We share the tools we used to help others understand how to recreate the work.

tools:
  - title: Github
    description: Social Project Platform
    url: http://github.com
  - title: Github Pages
    description: Free Project Hosting
    url: https://pages.github.com/

# ---------
# Blog
# ---------

permalink: /:categories/:year/:month/:day/:title
paginate: 25
paginate_path: "/blog/page:num"
blog_nav: yes

# ---------
# Support
# ---------

# URL to the issues page for this
support_title: Support
support_description: If you need any help, have questions, or would like to get involved, please use the following links.
support_email: info@apievangelist.com
support_twitter: kinlane

# ---------
# Roadmap
# ---------

roadmap_show: yes
roadmap_nav: yes

# ---------
# Change Log
# ---------

changelog_show: yes
changelog_nav: yes

# ---------
# General Settings
# ---------

#versioning your project is good
version:      1.1.1

#some configurations for the site
markdown:     kramdown


#what files should be excluded
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
